// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OspreyPulseAPI.Modules.Competitions.Infrastructure.Persistence;

#nullable disable

namespace OspreyPulseAPI.Modules.Competitions.Infrastructure.Migrations
{
    [DbContext(typeof(CompetitionsDbContext))]
    partial class CompetitionsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("competitions")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OspreyPulseAPI.Modules.Competitions.Domain.Channel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SportType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Channels", "competitions");
                });

            modelBuilder.Entity("OspreyPulseAPI.Modules.Competitions.Domain.Competition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AwayScore")
                        .HasColumnType("integer");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<short?>("CurrentPeriod")
                        .HasColumnType("smallint");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text");

                    b.Property<int>("HomeScore")
                        .HasColumnType("integer");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("integer");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<string>("TimeRemaining")
                        .HasColumnType("text");

                    b.Property<string>("Venue")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasFilter("\"ExternalId\" IS NOT NULL");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("SeasonId", "HomeTeamId", "AwayTeamId", "StartTime")
                        .IsUnique();

                    b.ToTable("competitions", "competitions");
                });

            modelBuilder.Entity("OspreyPulseAPI.Modules.Competitions.Domain.CompetitionRoster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompetitionId")
                        .HasColumnType("integer");

                    b.Property<short?>("LineupStatus")
                        .HasColumnType("smallint");

                    b.Property<string>("MinutesPlayed")
                        .HasColumnType("text")
                        .HasColumnName("minutes_played");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("PositionPlayed")
                        .HasColumnType("text")
                        .HasColumnName("position_played");

                    b.Property<decimal>("RatingAvg")
                        .HasColumnType("numeric");

                    b.Property<short?>("RoleType")
                        .HasColumnType("smallint");

                    b.Property<string>("Stats")
                        .HasColumnType("jsonb")
                        .HasColumnName("stats");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("competition_rosters", "competitions");
                });

            modelBuilder.Entity("OspreyPulseAPI.Modules.Competitions.Domain.League", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChannelId")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasFilter("\"ExternalId\" IS NOT NULL");

                    b.ToTable("Leagues", "competitions");
                });

            modelBuilder.Entity("OspreyPulseAPI.Modules.Competitions.Domain.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("DefaultPosition")
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short?>("HeightCm")
                        .HasColumnType("smallint");

                    b.Property<string>("Nationality")
                        .HasColumnType("text");

                    b.Property<short?>("WeightKg")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasFilter("\"ExternalId\" IS NOT NULL");

                    b.ToTable("Players", "competitions");
                });

            modelBuilder.Entity("OspreyPulseAPI.Modules.Competitions.Domain.PlayerTeamAssignment", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<short?>("JerseyNumber")
                        .HasColumnType("smallint");

                    b.Property<DateOnly?>("JoinedDate")
                        .HasColumnType("date");

                    b.HasKey("PlayerId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("player_team_assignments", "competitions");
                });

            modelBuilder.Entity("OspreyPulseAPI.Modules.Competitions.Domain.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LeagueId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId", "Label")
                        .IsUnique();

                    b.ToTable("Seasons", "competitions");
                });

            modelBuilder.Entity("OspreyPulseAPI.Modules.Competitions.Domain.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Conference")
                        .HasColumnType("text");

                    b.Property<string>("Division")
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text");

                    b.Property<int>("LeagueId")
                        .HasColumnType("integer");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nickname")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasFilter("\"ExternalId\" IS NOT NULL");

                    b.HasIndex("LeagueId");

                    b.ToTable("Teams", "competitions");
                });

            modelBuilder.Entity("OspreyPulseAPI.Modules.Competitions.Domain.Competition", b =>
                {
                    b.HasOne("OspreyPulseAPI.Modules.Competitions.Domain.Team", "AwayTeam")
                        .WithMany("AwayCompetitions")
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OspreyPulseAPI.Modules.Competitions.Domain.Team", "HomeTeam")
                        .WithMany("HomeCompetitions")
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OspreyPulseAPI.Modules.Competitions.Domain.Season", "Season")
                        .WithMany("Competitions")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("OspreyPulseAPI.Modules.Competitions.Domain.CompetitionRoster", b =>
                {
                    b.HasOne("OspreyPulseAPI.Modules.Competitions.Domain.Competition", "Competition")
                        .WithMany("Rosters")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OspreyPulseAPI.Modules.Competitions.Domain.Player", "Player")
                        .WithMany("CompetitionRosters")
                        .HasForeignKey("PlayerId");

                    b.HasOne("OspreyPulseAPI.Modules.Competitions.Domain.Team", "Team")
                        .WithMany("CompetitionRosters")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("OspreyPulseAPI.Modules.Competitions.Domain.League", b =>
                {
                    b.HasOne("OspreyPulseAPI.Modules.Competitions.Domain.Channel", "Channel")
                        .WithMany("Leagues")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("OspreyPulseAPI.Modules.Competitions.Domain.PlayerTeamAssignment", b =>
                {
                    b.HasOne("OspreyPulseAPI.Modules.Competitions.Domain.Player", "Player")
                        .WithMany("TeamAssignments")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OspreyPulseAPI.Modules.Competitions.Domain.Team", "Team")
                        .WithMany("PlayerAssignments")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("OspreyPulseAPI.Modules.Competitions.Domain.Season", b =>
                {
                    b.HasOne("OspreyPulseAPI.Modules.Competitions.Domain.League", "League")
                        .WithMany("Seasons")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("OspreyPulseAPI.Modules.Competitions.Domain.Team", b =>
                {
                    b.HasOne("OspreyPulseAPI.Modules.Competitions.Domain.League", "League")
                        .WithMany("Teams")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("OspreyPulseAPI.Modules.Competitions.Domain.Channel", b =>
                {
                    b.Navigation("Leagues");
                });

            modelBuilder.Entity("OspreyPulseAPI.Modules.Competitions.Domain.Competition", b =>
                {
                    b.Navigation("Rosters");
                });

            modelBuilder.Entity("OspreyPulseAPI.Modules.Competitions.Domain.League", b =>
                {
                    b.Navigation("Seasons");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("OspreyPulseAPI.Modules.Competitions.Domain.Player", b =>
                {
                    b.Navigation("CompetitionRosters");

                    b.Navigation("TeamAssignments");
                });

            modelBuilder.Entity("OspreyPulseAPI.Modules.Competitions.Domain.Season", b =>
                {
                    b.Navigation("Competitions");
                });

            modelBuilder.Entity("OspreyPulseAPI.Modules.Competitions.Domain.Team", b =>
                {
                    b.Navigation("AwayCompetitions");

                    b.Navigation("CompetitionRosters");

                    b.Navigation("HomeCompetitions");

                    b.Navigation("PlayerAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
