-- Apply the AddPostsTable migration by hand (use this when EF "database update" won't run it).
-- Run this entire script in your PostgreSQL DB (Supabase SQL editor or psql).

-- 1) Create the posts table (same as migration 20260225200000_AddPostsTable)
CREATE TABLE IF NOT EXISTS competitions.posts (
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NULL,
    "ChannelId" integer NOT NULL,
    "Title" character varying(255) NOT NULL,
    "Content" text NULL,
    "short_description" text NULL,
    "preview_img" text NULL,
    "origin_data" jsonb NULL,
    "external_id" text NULL,
    "Type" character varying(20) NOT NULL,
    "deleted_at" timestamp with time zone NULL,
    "created_at" timestamp with time zone NOT NULL,
    "last_bumped_at" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_posts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_posts_Channels_ChannelId" FOREIGN KEY ("ChannelId")
        REFERENCES competitions."Channels" ("Id") ON DELETE RESTRICT
);

-- 2) Indexes
CREATE UNIQUE INDEX IF NOT EXISTS "IX_posts_ChannelId_ExternalId"
    ON competitions.posts ("ChannelId", "external_id")
    WHERE "external_id" IS NOT NULL;

CREATE INDEX IF NOT EXISTS "IX_posts_ChannelId_Type_CreatedAt"
    ON competitions.posts ("ChannelId", "Type", "created_at");

-- 3) Grant permissions so the app role can INSERT/SELECT/UPDATE/DELETE
-- Replace "postgres" with the role from your connection string if different (e.g. Supabase project user).
GRANT ALL ON competitions.posts TO postgres;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA competitions TO postgres;

-- 4) Tell EF Core this migration is applied (so "database update" won't try to run it again)
INSERT INTO public."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260225200000_AddPostsTable', '10.0.3')
ON CONFLICT DO NOTHING;
